version: '3.3'

services:
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: main
      POSTGRES_PASSWORD: main
      POSTGRES_DB: message
    ports:
      - "5432:5432"

  php:
    build:
      context: ./php-fpm
    ports:
      - '9000:9000'
#    networks:
#      - message-network
    depends_on:
      - db
    volumes:
      - ../:/usr/share/nginx/html

  nginx:
    image: nginx:1.19.0-alpine
    restart: on-failure
    volumes:
      - '../:/usr/share/nginx/html'
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    depends_on:
      - php
    ports:
      - '88:80'